[server]
heartbeat_interval_ms = 1000

[batch]

[streaming]
checkpoint_interval_ms = 100

[storage]
shared_buffer_capacity_mb = 2048
sstable_size_mb = 256
block_size_kb = 1024
bloom_false_positive = 0.01
data_directory = "hummock_001"
block_cache_capacity_mb = 512
meta_cache_capacity_mb = 512
